version: '3'

services:
  peerone:
    image: peerone
    build:
      context: .
    ports:
      - "20000:80"
    networks:
      - peerone
    depends_on:
      - "redisdependency"
  peertwo:
    image: peertwo
    build:
      context: .
    ports:
      - "20001:81"
    networks:
      - peertwo
    depends_on:
      - "redispeertwodependency"

  redisdependency:
    image: redis:alpine
    ports:
      - "16379:6379"
    networks:
      - peerone

  redispeertwodependency:
    image: redis:alpine
    ports:
      - "16380:6380"
    networks:
      - peertwo

networks: 
    peerone:
        driver: bridge
    peertwo:
        driver: bridge